import React, { useState, useEffect } from 'react';
import { useTheme } from '../context/ThemeContext';

export const FullStackCodeStreamBackground: React.FC = () => {
  const { theme } = useTheme();
  const isLight = theme === 'light';
  const [isDesktop, setIsDesktop] = useState(() => typeof window !== 'undefined' && window.innerWidth >= 1024);

  useEffect(() => {
    const handleResize = () => {
      setIsDesktop(window.innerWidth >= 1024);
    };
    window.addEventListener('resize', handleResize, { passive: true });
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  if (!isDesktop) return null;

  return (
    <div
      className="fixed inset-0 z-0 pointer-events-none select-none flex justify-between px-2 sm:px-6 lg:px-10 xl:px-14 overflow-hidden"
      style={{ userSelect: 'none', WebkitUserSelect: 'none' }}
      aria-hidden="true"
    >

      {/* ── Left Side: Frontend React 19 + TypeScript + WebGL Streaming Column ── */}
      <div className="hidden lg:flex flex-col w-[310px] xl:w-[410px] 2xl:w-[480px] opacity-20 dark:opacity-25 light:opacity-20 pointer-events-none select-none animate-code-stream font-mono text-[11px] leading-relaxed">
        {/* Block 1 */}
        <div className="space-y-1 py-4 shrink-0">
          <div className="text-[11px] font-bold font-hud tracking-widest text-cyan-500/90 dark:text-cyan-400/90 pb-2.5">// ── FRONTEND MATRIX: REACT 19 + TYPESCRIPT (TSX) ──</div>
          <div><span style={{ color: '#64748b' }}>01 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>React, {'{'} useState, useEffect, useMemo {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'react'</span>;</div>
          <div><span style={{ color: '#64748b' }}>02 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>{'{'} Canvas, useFrame {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'@react-three/fiber'</span>;</div>
          <div><span style={{ color: '#64748b' }}>03 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>{'{'} useFullStackEngine {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'@jp/core-hooks'</span>;</div>
          <div><span style={{ color: '#64748b' }}>04 </span></div>
          <div><span style={{ color: '#64748b' }}>05 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>interface </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>FrontendState </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>06 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span>;</div>
          <div><span style={{ color: '#64748b' }}>07 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>stack: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React 19 / TS 5 / Vite 6"</span>;</div>
          <div><span style={{ color: '#64748b' }}>08 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>styling: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Tailwind CSS & Vanilla CSS"</span>;</div>
          <div><span style={{ color: '#64748b' }}>09 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>fpsLimit: </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>120</span>;</div>
          <div><span style={{ color: '#64748b' }}>10 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>status: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"FULLSTACK_ONLINE_100"</span>;</div>
          <div><span style={{ color: '#64748b' }}>11 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
          <div><span style={{ color: '#64748b' }}>12 </span></div>
          <div><span style={{ color: '#64748b' }}>13 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>export const </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>PortfolioCore</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>: React.FC = () =&gt; {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>14 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>const </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>[state, setState] = </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useState</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>&lt;FrontendState&gt;({'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>15 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span>,</div>
          <div><span style={{ color: '#64748b' }}>16 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>stack: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React 19"</span>,</div>
          <div><span style={{ color: '#64748b' }}>17 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>fpsLimit: </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>120</span></div>
          <div><span style={{ color: '#64748b' }}>18 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'});</span></div>
          <div><span style={{ color: '#64748b' }}>19 </span></div>
          <div><span style={{ color: '#64748b' }}>20 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>const </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'} dispatchEngine {'}'} = </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useFullStackEngine</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>();</span></div>
          <div><span style={{ color: '#64748b' }}>21 </span></div>
          <div><span style={{ color: '#64748b' }}>22 </span><span className="ml-3" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useEffect</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(() =&gt; {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>23 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>dispatchEngine</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>({'{'} mode: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"FULL_STACK_HUD"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, sync: </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>true</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}> {'}'});</span></div>
          <div><span style={{ color: '#64748b' }}>24 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}, []);</span></div>
          <div><span style={{ color: '#64748b' }}>25 </span></div>
          <div><span style={{ color: '#64748b' }}>26 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>return </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span></div>
          <div><span style={{ color: '#64748b' }}>27 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>CyberContainer </span><span style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>active</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>=</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>true</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>28 </span><span className="ml-9" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>HeroProfile </span><span style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>=</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}state.developer{'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> /&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>29 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;/</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>CyberContainer</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>30 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>31 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'};</span></div>
        </div>

        {/* Block 2 */}
        <div className="space-y-1 py-4 shrink-0">
          <div className="text-[11px] font-bold font-hud tracking-widest text-cyan-500/90 dark:text-cyan-400/90 pb-2.5">// ── FRONTEND MATRIX: REACT 19 + TYPESCRIPT (TSX) ──</div>
          <div><span style={{ color: '#64748b' }}>01 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>React, {'{'} useState, useEffect, useMemo {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'react'</span>;</div>
          <div><span style={{ color: '#64748b' }}>02 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>{'{'} Canvas, useFrame {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'@react-three/fiber'</span>;</div>
          <div><span style={{ color: '#64748b' }}>03 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>{'{'} useFullStackEngine {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'@jp/core-hooks'</span>;</div>
          <div><span style={{ color: '#64748b' }}>04 </span></div>
          <div><span style={{ color: '#64748b' }}>05 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>interface </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>FrontendState </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>06 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span>;</div>
          <div><span style={{ color: '#64748b' }}>07 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>stack: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React 19 / TS 5 / Vite 6"</span>;</div>
          <div><span style={{ color: '#64748b' }}>08 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>styling: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Tailwind CSS & Vanilla CSS"</span>;</div>
          <div><span style={{ color: '#64748b' }}>09 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>fpsLimit: </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>120</span>;</div>
          <div><span style={{ color: '#64748b' }}>10 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>status: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"FULLSTACK_ONLINE_100"</span>;</div>
          <div><span style={{ color: '#64748b' }}>11 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
          <div><span style={{ color: '#64748b' }}>12 </span></div>
          <div><span style={{ color: '#64748b' }}>13 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>export const </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>PortfolioCore</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>: React.FC = () =&gt; {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>14 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>const </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>[state, setState] = </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useState</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>&lt;FrontendState&gt;({'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>15 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span>,</div>
          <div><span style={{ color: '#64748b' }}>16 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>stack: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React 19"</span>,</div>
          <div><span style={{ color: '#64748b' }}>17 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>fpsLimit: </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>120</span></div>
          <div><span style={{ color: '#64748b' }}>18 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'});</span></div>
          <div><span style={{ color: '#64748b' }}>19 </span></div>
          <div><span style={{ color: '#64748b' }}>20 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>const </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'} dispatchEngine {'}'} = </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useFullStackEngine</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>();</span></div>
          <div><span style={{ color: '#64748b' }}>21 </span></div>
          <div><span style={{ color: '#64748b' }}>22 </span><span className="ml-3" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useEffect</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(() =&gt; {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>23 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>dispatchEngine</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>({'{'} mode: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"FULL_STACK_HUD"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, sync: </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>true</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}> {'}'});</span></div>
          <div><span style={{ color: '#64748b' }}>24 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}, []);</span></div>
          <div><span style={{ color: '#64748b' }}>25 </span></div>
          <div><span style={{ color: '#64748b' }}>26 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>return </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span></div>
          <div><span style={{ color: '#64748b' }}>27 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>CyberContainer </span><span style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>active</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>=</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>true</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>28 </span><span className="ml-9" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>HeroProfile </span><span style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>=</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}state.developer{'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> /&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>29 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;/</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>CyberContainer</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>30 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>31 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'};</span></div>
        </div>

        {/* Block 3 */}
        <div className="space-y-1 py-4 shrink-0">
          <div className="text-[11px] font-bold font-hud tracking-widest text-cyan-500/90 dark:text-cyan-400/90 pb-2.5">// ── FRONTEND MATRIX: REACT 19 + TYPESCRIPT (TSX) ──</div>
          <div><span style={{ color: '#64748b' }}>01 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>React, {'{'} useState, useEffect, useMemo {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'react'</span>;</div>
          <div><span style={{ color: '#64748b' }}>02 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>{'{'} Canvas, useFrame {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'@react-three/fiber'</span>;</div>
          <div><span style={{ color: '#64748b' }}>03 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>{'{'} useFullStackEngine {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'@jp/core-hooks'</span>;</div>
          <div><span style={{ color: '#64748b' }}>04 </span></div>
          <div><span style={{ color: '#64748b' }}>05 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>interface </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>FrontendState </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>06 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span>;</div>
          <div><span style={{ color: '#64748b' }}>07 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>stack: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React 19 / TS 5 / Vite 6"</span>;</div>
          <div><span style={{ color: '#64748b' }}>08 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>styling: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Tailwind CSS & Vanilla CSS"</span>;</div>
          <div><span style={{ color: '#64748b' }}>09 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>fpsLimit: </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>120</span>;</div>
          <div><span style={{ color: '#64748b' }}>10 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>status: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"FULLSTACK_ONLINE_100"</span>;</div>
          <div><span style={{ color: '#64748b' }}>11 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
          <div><span style={{ color: '#64748b' }}>12 </span></div>
          <div><span style={{ color: '#64748b' }}>13 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>export const </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>PortfolioCore</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>: React.FC = () =&gt; {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>14 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>const </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>[state, setState] = </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useState</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>&lt;FrontendState&gt;({'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>15 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span>,</div>
          <div><span style={{ color: '#64748b' }}>16 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>stack: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React 19"</span>,</div>
          <div><span style={{ color: '#64748b' }}>17 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>fpsLimit: </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>120</span></div>
          <div><span style={{ color: '#64748b' }}>18 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'});</span></div>
          <div><span style={{ color: '#64748b' }}>19 </span></div>
          <div><span style={{ color: '#64748b' }}>20 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>const </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'} dispatchEngine {'}'} = </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useFullStackEngine</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>();</span></div>
          <div><span style={{ color: '#64748b' }}>21 </span></div>
          <div><span style={{ color: '#64748b' }}>22 </span><span className="ml-3" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useEffect</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(() =&gt; {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>23 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>dispatchEngine</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>({'{'} mode: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"FULL_STACK_HUD"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, sync: </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>true</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}> {'}'});</span></div>
          <div><span style={{ color: '#64748b' }}>24 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}, []);</span></div>
          <div><span style={{ color: '#64748b' }}>25 </span></div>
          <div><span style={{ color: '#64748b' }}>26 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>return </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span></div>
          <div><span style={{ color: '#64748b' }}>27 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>CyberContainer </span><span style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>active</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>=</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>true</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>28 </span><span className="ml-9" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>HeroProfile </span><span style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>=</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}state.developer{'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> /&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>29 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;/</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>CyberContainer</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>30 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>31 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'};</span></div>
        </div>

        {/* Block 4 */}
        <div className="space-y-1 py-4 shrink-0">
          <div className="text-[11px] font-bold font-hud tracking-widest text-cyan-500/90 dark:text-cyan-400/90 pb-2.5">// ── FRONTEND MATRIX: REACT 19 + TYPESCRIPT (TSX) ──</div>
          <div><span style={{ color: '#64748b' }}>01 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>React, {'{'} useState, useEffect, useMemo {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'react'</span>;</div>
          <div><span style={{ color: '#64748b' }}>02 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>{'{'} Canvas, useFrame {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'@react-three/fiber'</span>;</div>
          <div><span style={{ color: '#64748b' }}>03 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>{'{'} useFullStackEngine {'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> from </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>'@jp/core-hooks'</span>;</div>
          <div><span style={{ color: '#64748b' }}>04 </span></div>
          <div><span style={{ color: '#64748b' }}>05 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>interface </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>FrontendState </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>06 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span>;</div>
          <div><span style={{ color: '#64748b' }}>07 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>stack: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React 19 / TS 5 / Vite 6"</span>;</div>
          <div><span style={{ color: '#64748b' }}>08 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>styling: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Tailwind CSS & Vanilla CSS"</span>;</div>
          <div><span style={{ color: '#64748b' }}>09 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>fpsLimit: </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>120</span>;</div>
          <div><span style={{ color: '#64748b' }}>10 </span><span className="ml-3" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>status: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"FULLSTACK_ONLINE_100"</span>;</div>
          <div><span style={{ color: '#64748b' }}>11 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
          <div><span style={{ color: '#64748b' }}>12 </span></div>
          <div><span style={{ color: '#64748b' }}>13 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>export const </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>PortfolioCore</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>: React.FC = () =&gt; {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>14 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>const </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>[state, setState] = </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useState</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>&lt;FrontendState&gt;({'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>15 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span>,</div>
          <div><span style={{ color: '#64748b' }}>16 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>stack: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React 19"</span>,</div>
          <div><span style={{ color: '#64748b' }}>17 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>fpsLimit: </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>120</span></div>
          <div><span style={{ color: '#64748b' }}>18 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'});</span></div>
          <div><span style={{ color: '#64748b' }}>19 </span></div>
          <div><span style={{ color: '#64748b' }}>20 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>const </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'} dispatchEngine {'}'} = </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useFullStackEngine</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>();</span></div>
          <div><span style={{ color: '#64748b' }}>21 </span></div>
          <div><span style={{ color: '#64748b' }}>22 </span><span className="ml-3" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>useEffect</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(() =&gt; {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>23 </span><span className="ml-6" style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>dispatchEngine</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>({'{'} mode: </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"FULL_STACK_HUD"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, sync: </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>true</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}> {'}'});</span></div>
          <div><span style={{ color: '#64748b' }}>24 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}, []);</span></div>
          <div><span style={{ color: '#64748b' }}>25 </span></div>
          <div><span style={{ color: '#64748b' }}>26 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>return </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span></div>
          <div><span style={{ color: '#64748b' }}>27 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>CyberContainer </span><span style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>active</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>=</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>true</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>28 </span><span className="ml-9" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>HeroProfile </span><span style={{ color: isLight ? '#0284c7' : '#38bdf8' }}>developer</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>=</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}state.developer{'}'}</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}> /&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>29 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&lt;/</span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>CyberContainer</span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>&gt;</span></div>
          <div><span style={{ color: '#64748b' }}>30 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>31 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'};</span></div>
        </div>
      </div>

      {/* ── Right Side: Backend Java Spring Boot + JPA Streaming Column ── */}
      <div
        className="hidden lg:flex flex-col w-[310px] xl:w-[410px] 2xl:w-[480px] opacity-20 dark:opacity-25 light:opacity-20 pointer-events-none select-none animate-code-stream font-mono text-[11px] leading-relaxed"
        style={{ animationDelay: '-16s' }}
      >
        {/* Block 1 */}
        <div className="space-y-1 py-4 shrink-0">
          <div className="text-[11px] font-bold font-hud tracking-widest text-purple-500/90 dark:text-purple-400/90 pb-2.5">// ── BACKEND MATRIX: JAVA SPRING BOOT + JPA ──</div>
          <div><span style={{ color: '#64748b' }}>01 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>package </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>com.ericxjason.portfolio.controller;</span></div>
          <div><span style={{ color: '#64748b' }}>02 </span></div>
          <div><span style={{ color: '#64748b' }}>03 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>org.springframework.web.bind.annotation.*</span>;</div>
          <div><span style={{ color: '#64748b' }}>04 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>org.springframework.beans.factory.annotation.Autowired</span>;</div>
          <div><span style={{ color: '#64748b' }}>05 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>com.ericxjason.portfolio.model.EngineerProfile</span>;</div>
          <div><span style={{ color: '#64748b' }}>06 </span></div>
          <div><span style={{ color: '#64748b' }}>07 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@RestController</span></div>
          <div><span style={{ color: '#64748b' }}>08 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@RequestMapping</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"/api/v1/engineer"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>09 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@CrossOrigin</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(origins = </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"https://ericxjason.github.io"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>10 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>public class </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfileController </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>11 </span></div>
          <div><span style={{ color: '#64748b' }}>12 </span><span className="ml-3" style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@Autowired</span></div>
          <div><span style={{ color: '#64748b' }}>13 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>private </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>PortfolioService </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>portfolioService;</span></div>
          <div><span style={{ color: '#64748b' }}>14 </span></div>
          <div><span style={{ color: '#64748b' }}>15 </span><span className="ml-3" style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@GetMapping</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"/profile"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>16 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>public </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>ResponseEntity&lt;EngineerProfile&gt; </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>getProfile</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>() {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>17 </span><span className="ml-6" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfile </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile = </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>new </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfile</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>();</span></div>
          <div><span style={{ color: '#64748b' }}>18 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setName(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>19 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setRole(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Full-Stack Software Engineer"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>20 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setDegree(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Master of Fine Arts (M.F.A.)"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>21 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setSkills(List.of(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Java Spring"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"TypeScript"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>));</span></div>
          <div><span style={{ color: '#64748b' }}>22 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setStatus(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"200_OK_FULLSTACK"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>23 </span></div>
          <div><span style={{ color: '#64748b' }}>24 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>return </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>ResponseEntity.ok(profile);</span></div>
          <div><span style={{ color: '#64748b' }}>25 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
          <div><span style={{ color: '#64748b' }}>26 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
        </div>

        {/* Block 2 */}
        <div className="space-y-1 py-4 shrink-0">
          <div className="text-[11px] font-bold font-hud tracking-widest text-purple-500/90 dark:text-purple-400/90 pb-2.5">// ── BACKEND MATRIX: JAVA SPRING BOOT + JPA ──</div>
          <div><span style={{ color: '#64748b' }}>01 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>package </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>com.ericxjason.portfolio.controller;</span></div>
          <div><span style={{ color: '#64748b' }}>02 </span></div>
          <div><span style={{ color: '#64748b' }}>03 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>org.springframework.web.bind.annotation.*</span>;</div>
          <div><span style={{ color: '#64748b' }}>04 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>org.springframework.beans.factory.annotation.Autowired</span>;</div>
          <div><span style={{ color: '#64748b' }}>05 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>com.ericxjason.portfolio.model.EngineerProfile</span>;</div>
          <div><span style={{ color: '#64748b' }}>06 </span></div>
          <div><span style={{ color: '#64748b' }}>07 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@RestController</span></div>
          <div><span style={{ color: '#64748b' }}>08 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@RequestMapping</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"/api/v1/engineer"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>09 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@CrossOrigin</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(origins = </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"https://ericxjason.github.io"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>10 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>public class </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfileController </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>11 </span></div>
          <div><span style={{ color: '#64748b' }}>12 </span><span className="ml-3" style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@Autowired</span></div>
          <div><span style={{ color: '#64748b' }}>13 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>private </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>PortfolioService </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>portfolioService;</span></div>
          <div><span style={{ color: '#64748b' }}>14 </span></div>
          <div><span style={{ color: '#64748b' }}>15 </span><span className="ml-3" style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@GetMapping</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"/profile"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>16 </span><span className="ml-3" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>public </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>ResponseEntity&lt;EngineerProfile&gt; </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>getProfile</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>() {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>17 </span><span className="ml-6" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfile </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile = </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>new </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfile</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>();</span></div>
          <div><span style={{ color: '#64748b' }}>18 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setName(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>19 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setRole(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Full-Stack Software Engineer"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>20 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setDegree(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Master of Fine Arts (M.F.A.)"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>21 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setSkills(List.of(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Java Spring"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"TypeScript"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>));</span></div>
          <div><span style={{ color: '#64748b' }}>22 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setStatus(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"200_OK_FULLSTACK"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>23 </span></div>
          <div><span style={{ color: '#64748b' }}>24 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>return </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>ResponseEntity.ok(profile);</span></div>
          <div><span style={{ color: '#64748b' }}>25 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
          <div><span style={{ color: '#64748b' }}>26 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
        </div>

        {/* Block 3 */}
        <div className="space-y-1 py-4 shrink-0">
          <div className="text-[11px] font-bold font-hud tracking-widest text-purple-500/90 dark:text-purple-400/90 pb-2.5">// ── BACKEND MATRIX: JAVA SPRING BOOT + JPA ──</div>
          <div><span style={{ color: '#64748b' }}>01 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>package </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>com.ericxjason.portfolio.controller;</span></div>
          <div><span style={{ color: '#64748b' }}>02 </span></div>
          <div><span style={{ color: '#64748b' }}>03 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>org.springframework.web.bind.annotation.*</span>;</div>
          <div><span style={{ color: '#64748b' }}>04 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>org.springframework.beans.factory.annotation.Autowired</span>;</div>
          <div><span style={{ color: '#64748b' }}>05 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>com.ericxjason.portfolio.model.EngineerProfile</span>;</div>
          <div><span style={{ color: '#64748b' }}>06 </span></div>
          <div><span style={{ color: '#64748b' }}>07 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@RestController</span></div>
          <div><span style={{ color: '#64748b' }}>08 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@RequestMapping</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"/api/v1/engineer"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>09 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@CrossOrigin</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(origins = </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"https://ericxjason.github.io"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>10 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>public class </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfileController </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>11 </span></div>
          <div><span style={{ color: '#64748b' }}>12 </span><span className="ml-3" style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@Autowired</span></div>
          <div><span style={{ color: '#64748b' }}>13 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>private </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>PortfolioService </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>portfolioService;</span></div>
          <div><span style={{ color: '#64748b' }}>14 </span></div>
          <div><span style={{ color: '#64748b' }}>15 </span><span className="ml-3" style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@GetMapping</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"/profile"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>16 </span><span className="ml-3" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>public </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>ResponseEntity&lt;EngineerProfile&gt; </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>getProfile</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>() {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>17 </span><span className="ml-6" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfile </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile = </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>new </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfile</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>();</span></div>
          <div><span style={{ color: '#64748b' }}>18 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setName(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>19 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setRole(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Full-Stack Software Engineer"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>20 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setDegree(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Master of Fine Arts (M.F.A.)"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>21 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setSkills(List.of(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Java Spring"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"TypeScript"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>));</span></div>
          <div><span style={{ color: '#64748b' }}>22 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setStatus(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"200_OK_FULLSTACK"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>23 </span></div>
          <div><span style={{ color: '#64748b' }}>24 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>return </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>ResponseEntity.ok(profile);</span></div>
          <div><span style={{ color: '#64748b' }}>25 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
          <div><span style={{ color: '#64748b' }}>26 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
        </div>

        {/* Block 4 */}
        <div className="space-y-1 py-4 shrink-0">
          <div className="text-[11px] font-bold font-hud tracking-widest text-purple-500/90 dark:text-purple-400/90 pb-2.5">// ── BACKEND MATRIX: JAVA SPRING BOOT + JPA ──</div>
          <div><span style={{ color: '#64748b' }}>01 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>package </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>com.ericxjason.portfolio.controller;</span></div>
          <div><span style={{ color: '#64748b' }}>02 </span></div>
          <div><span style={{ color: '#64748b' }}>03 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>org.springframework.web.bind.annotation.*</span>;</div>
          <div><span style={{ color: '#64748b' }}>04 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>org.springframework.beans.factory.annotation.Autowired</span>;</div>
          <div><span style={{ color: '#64748b' }}>05 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>import </span><span style={{ color: isLight ? '#0284c7' : '#00f0ff' }}>com.ericxjason.portfolio.model.EngineerProfile</span>;</div>
          <div><span style={{ color: '#64748b' }}>06 </span></div>
          <div><span style={{ color: '#64748b' }}>07 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@RestController</span></div>
          <div><span style={{ color: '#64748b' }}>08 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@RequestMapping</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"/api/v1/engineer"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>09 </span><span style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@CrossOrigin</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(origins = </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"https://ericxjason.github.io"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>10 </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>public class </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfileController </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>11 </span></div>
          <div><span style={{ color: '#64748b' }}>12 </span><span className="ml-3" style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@Autowired</span></div>
          <div><span style={{ color: '#64748b' }}>13 </span><span className="ml-3" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>private </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>PortfolioService </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>portfolioService;</span></div>
          <div><span style={{ color: '#64748b' }}>14 </span></div>
          <div><span style={{ color: '#64748b' }}>15 </span><span className="ml-3" style={{ color: isLight ? '#d97706' : '#fbbf24' }}>@GetMapping</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"/profile"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>)</span></div>
          <div><span style={{ color: '#64748b' }}>16 </span><span className="ml-3" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>public </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>ResponseEntity&lt;EngineerProfile&gt; </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>getProfile</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>() {'{'}</span></div>
          <div><span style={{ color: '#64748b' }}>17 </span><span className="ml-6" style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfile </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile = </span><span style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>new </span><span style={{ color: isLight ? '#2563eb' : '#60a5fa' }}>EngineerProfile</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>();</span></div>
          <div><span style={{ color: '#64748b' }}>18 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setName(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"許哲誠 (HSU, CHE-CHENG)"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>19 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setRole(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Full-Stack Software Engineer"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>20 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setDegree(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Master of Fine Arts (M.F.A.)"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>21 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setSkills(List.of(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"Java Spring"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"React"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>, </span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"TypeScript"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>));</span></div>
          <div><span style={{ color: '#64748b' }}>22 </span><span className="ml-6" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>profile.setStatus(</span><span style={{ color: isLight ? '#047857' : '#34d399' }}>"200_OK_FULLSTACK"</span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>);</span></div>
          <div><span style={{ color: '#64748b' }}>23 </span></div>
          <div><span style={{ color: '#64748b' }}>24 </span><span className="ml-6" style={{ color: isLight ? '#7e22ce' : '#c084fc' }}>return </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>ResponseEntity.ok(profile);</span></div>
          <div><span style={{ color: '#64748b' }}>25 </span><span className="ml-3" style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
          <div><span style={{ color: '#64748b' }}>26 </span><span style={{ color: isLight ? '#0f172a' : '#f8fafc' }}>{'}'}</span></div>
        </div>
      </div>
    </div>
  );
};
