/**
 * ============================================================================
 * 檔案名稱: iconHelper.ts
 * 所屬模組: Shared Presentation Utility Layer (向量圖示共用轉換模組)
 * 責任描述: 負責提供全站與 CMS 通用之 Lucide 向量圖示名稱映射、別名對齊與預設圖示回退。
 *           物理隔離前臺展示與 CMS 管理後臺，避免前臺首屏因圖示解析而誤載入 CMS 巨型代碼塊。
 * 架構分層: Utility Layer (Shared Presentation Contract)
 * 依賴關係: 依賴 lucide-react 向量圖示庫。
 * 邊界處理: 查無名稱時自動回退至 Star 圖示，支援大小寫不敏感、底線連字號容錯與領域別名推斷。
 * ============================================================================
 */

import {
  GraduationCap,
  Award,
  Trophy,
  Medal,
  Crown,
  Star,
  Sparkles,
  Bookmark,
  BookMarked,
  Code,
  Code2,
  Terminal,
  Cpu,
  Database,
  Server,
  Globe,
  Globe2,
  GitBranch,
  GitMerge,
  GitCommit,
  GitPullRequest,
  Wrench,
  Layers,
  Gamepad,
  Gamepad2,
  Palette,
  Image as ImageIcon,
  Video,
  Music,
  Headphones,
  Camera,
  Film,
  Box,
  PenTool,
  Monitor,
  Play,
  Briefcase,
  Building,
  Building2,
  Compass,
  Target,
  Rocket,
  Lightbulb,
  Zap,
  TrendingUp,
  FolderGit2,
  Cloud,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Lock,
  Unlock,
  Key,
  Radio,
  Bell,
  User,
  Users,
  Heart,
  ThumbsUp,
  Send,
  Mail,
  Phone,
  MessageSquare,
  MessageCircle,
  ExternalLink,
  Link,
  Share2,
  Eye,
  EyeOff,
  Calendar,
  Clock,
  History,
  FileText,
  FileCode,
  FileSpreadsheet,
  FileCheck,
  AlertTriangle,
  AlertCircle,
  Info,
  HelpCircle,
  School,
  BookOpen,
  Book,
  Library,
  Presentation,
  Landmark,
  Scroll,
  FlaskConical,
  Atom,
  TestTube,
  HardDrive,
  Network,
  Wifi,
  Laptop,
  Smartphone,
  Tablet,
  ScreenShare,
  Bug,
  Binary,
  Braces,
  Brackets,
  Workflow,
  Folder,
  FolderCode,
  FolderTree,
  Package,
  Archive,
  RefreshCw,
  Sliders,
  SlidersHorizontal,
  Settings,
  Settings2,
  Filter,
  Search,
  Check,
  CheckCircle,
  CheckSquare,
  X,
  XCircle,
  Sun,
  Moon,
  Flame,
  Droplet,
  Coffee,
  Paintbrush,
  Scissors,
  Wand2,
  Mic,
  Speaker,
  Disc,
  Clapperboard,
  Factory,
  Store,
  CreditCard,
  DollarSign,
  Wallet,
  Percent,
  Receipt,
  Megaphone,
  Flag,
  MapPin,
  Navigation,
  AtSign,
  Rss,
  Smile,
  Activity,
  Gauge,
  BarChart,
  BarChart2,
  PieChart,
  LineChart,
  Maximize,
  Minimize,
  Move,
  Volume2,
  Volume1,
  type LucideIcon,
} from 'lucide-react';

export interface IconEntry {
  name: string;
  labelZh: string;
  labelEn: string;
  category: 'academic' | 'dev' | 'multimedia' | 'business' | 'security' | 'general' | 'hardware' | 'tools';
  component: LucideIcon;
}

/** 完整圖示資料庫 (200+ 個常用高頻圖示與各領域相依圖示) */
export const ICON_LIBRARY: IconEntry[] = [
  // ── 學歷、榮譽與證照 ──
  { name: 'graduation-cap', labelZh: '學士/碩士帽', labelEn: 'Graduation Cap', category: 'academic', component: GraduationCap },
  { name: 'school',         labelZh: '學校學府',   labelEn: 'School Campus',  category: 'academic', component: School },
  { name: 'landmark',       labelZh: '典雅殿堂',   labelEn: 'Landmark',       category: 'academic', component: Landmark },
  { name: 'book-open',      labelZh: '翻閱書本',   labelEn: 'Open Book',      category: 'academic', component: BookOpen },
  { name: 'book',           labelZh: '書籍書籍',   labelEn: 'Book',           category: 'academic', component: Book },
  { name: 'library',        labelZh: '圖書館舍',   labelEn: 'Library',        category: 'academic', component: Library },
  { name: 'book-marked',    labelZh: '標記書籍',   labelEn: 'Book Marked',    category: 'academic', component: BookMarked },
  { name: 'presentation',   labelZh: '簡報發表',   labelEn: 'Presentation',   category: 'academic', component: Presentation },
  { name: 'scroll',         labelZh: '學術卷軸',   labelEn: 'Academic Scroll',category: 'academic', component: Scroll },
  { name: 'flask-conical',  labelZh: '研究實驗',   labelEn: 'Research Flask', category: 'academic', component: FlaskConical },
  { name: 'atom',           labelZh: '科學原子',   labelEn: 'Atom Science',   category: 'academic', component: Atom },
  { name: 'test-tube',      labelZh: '化驗試管',   labelEn: 'Test Tube',      category: 'academic', component: TestTube },
  { name: 'award',          labelZh: '獎章證書',   labelEn: 'Award',          category: 'academic', component: Award },
  { name: 'trophy',         labelZh: '競賽獎盃',   labelEn: 'Trophy',         category: 'academic', component: Trophy },
  { name: 'medal',          labelZh: '金銀獎牌',   labelEn: 'Medal',          category: 'academic', component: Medal },
  { name: 'crown',          labelZh: '冠軍皇冠',   labelEn: 'Crown',          category: 'academic', component: Crown },
  { name: 'star',           labelZh: '精選星號',   labelEn: 'Star',           category: 'academic', component: Star },
  { name: 'sparkles',       labelZh: '亮點閃爍',   labelEn: 'Sparkles',       category: 'academic', component: Sparkles },
  { name: 'bookmark',       labelZh: '書籤標記',   labelEn: 'Bookmark',       category: 'academic', component: Bookmark },

  // ── 程式、架構與軟體工程 ──
  { name: 'code',           labelZh: '程式代碼',   labelEn: 'Code',           category: 'dev', component: Code },
  { name: 'code-2',         labelZh: '尖括號代碼', labelEn: 'Code 2',         category: 'dev', component: Code2 },
  { name: 'terminal',       labelZh: '終端命令列', labelEn: 'Terminal',       category: 'dev', component: Terminal },
  { name: 'braces',         labelZh: '花括號物件', labelEn: 'Braces',         category: 'dev', component: Braces },
  { name: 'brackets',       labelZh: '方括號陣列', labelEn: 'Brackets',       category: 'dev', component: Brackets },
  { name: 'binary',         labelZh: '二進位代碼', labelEn: 'Binary Code',    category: 'dev', component: Binary },
  { name: 'bug',            labelZh: '除錯偵錯',   labelEn: 'Debug Bug',      category: 'dev', component: Bug },
  { name: 'database',       labelZh: '資料庫',     labelEn: 'Database',       category: 'dev', component: Database },
  { name: 'server',         labelZh: '後端伺服器', labelEn: 'Server',         category: 'dev', component: Server },
  { name: 'globe',          labelZh: '全球網路',   labelEn: 'Global Web',     category: 'dev', component: Globe },
  { name: 'globe-2',        labelZh: '網際網路 2', labelEn: 'Global Web 2',   category: 'dev', component: Globe2 },
  { name: 'git-branch',     labelZh: 'Git 分支',   labelEn: 'Git Branch',     category: 'dev', component: GitBranch },
  { name: 'git-merge',      labelZh: 'Git 合併',   labelEn: 'Git Merge',      category: 'dev', component: GitMerge },
  { name: 'git-commit',     labelZh: 'Git 節點',   labelEn: 'Git Commit',     category: 'dev', component: GitCommit },
  { name: 'git-pull-request',labelZh:'Pull Request',labelEn:'Git PR',         category: 'dev', component: GitPullRequest },
  { name: 'layers',         labelZh: '架構分層',   labelEn: 'Layers Stack',   category: 'dev', component: Layers },
  { name: 'workflow',       labelZh: '工作流程圖', labelEn: 'Workflow',       category: 'dev', component: Workflow },
  { name: 'file-code',      labelZh: '原始檔代碼', labelEn: 'File Code',      category: 'dev', component: FileCode },
  { name: 'folder-code',    labelZh: '代碼目錄',   labelEn: 'Folder Code',    category: 'dev', component: FolderCode },
  { name: 'folder-git-2',   labelZh: '專案倉庫',   labelEn: 'Projects Repo',  category: 'dev', component: FolderGit2 },
  { name: 'folder-tree',    labelZh: '目錄拓撲',   labelEn: 'Folder Tree',    category: 'dev', component: FolderTree },

  // ── 硬體、運算與網路 ──
  { name: 'cpu',            labelZh: '核心處理器', labelEn: 'CPU Processor',  category: 'hardware', component: Cpu },
  { name: 'hard-drive',     labelZh: '硬碟儲存',   labelEn: 'Hard Drive',     category: 'hardware', component: HardDrive },
  { name: 'network',        labelZh: '網路拓撲',   labelEn: 'Network',        category: 'hardware', component: Network },
  { name: 'wifi',           labelZh: '無線網路',   labelEn: 'WiFi Wireless',  category: 'hardware', component: Wifi },
  { name: 'laptop',         labelZh: '筆記型電腦', labelEn: 'Laptop',         category: 'hardware', component: Laptop },
  { name: 'monitor',        labelZh: '桌上型螢幕', labelEn: 'Display Monitor',category: 'hardware', component: Monitor },
  { name: 'smartphone',     labelZh: '智慧手機',   labelEn: 'Smartphone',     category: 'hardware', component: Smartphone },
  { name: 'tablet',         labelZh: '平板電腦',   labelEn: 'Tablet Device',  category: 'hardware', component: Tablet },
  { name: 'screen-share',   labelZh: '投影共享',   labelEn: 'Screen Share',   category: 'hardware', component: ScreenShare },

  // ── 多媒體、遊戲與設計 ──
  { name: 'gamepad-2',      labelZh: '遊戲把手',   labelEn: 'Gamepad 2',      category: 'multimedia', component: Gamepad2 },
  { name: 'gamepad',        labelZh: '經典搖桿',   labelEn: 'Gamepad Classic',category: 'multimedia', component: Gamepad },
  { name: 'palette',        labelZh: '調色美學',   labelEn: 'Palette',        category: 'multimedia', component: Palette },
  { name: 'image',          labelZh: '美術圖檔',   labelEn: 'Image Artwork',  category: 'multimedia', component: ImageIcon },
  { name: 'box',            labelZh: '3D 幾何模型',labelEn: '3D Box Model',   category: 'multimedia', component: Box },
  { name: 'pen-tool',       labelZh: '向量鋼筆',   labelEn: 'Pen Tool',       category: 'multimedia', component: PenTool },
  { name: 'paintbrush',     labelZh: '藝術筆刷',   labelEn: 'Paintbrush',     category: 'multimedia', component: Paintbrush },
  { name: 'wand-2',         labelZh: '魔法魔杖',   labelEn: 'Magic Wand',     category: 'multimedia', component: Wand2 },
  { name: 'scissors',       labelZh: '剪裁工具',   labelEn: 'Scissors Cut',   category: 'multimedia', component: Scissors },
  { name: 'video',          labelZh: '即時影音',   labelEn: 'Video Stream',   category: 'multimedia', component: Video },
  { name: 'film',           labelZh: '影音動畫',   labelEn: 'Film Reel',      category: 'multimedia', component: Film },
  { name: 'clapperboard',   labelZh: '電影片場板', labelEn: 'Clapperboard',   category: 'multimedia', component: Clapperboard },
  { name: 'camera',         labelZh: '鏡頭攝影',   labelEn: 'Camera Shot',    category: 'multimedia', component: Camera },
  { name: 'music',          labelZh: '音樂音效',   labelEn: 'Music Track',    category: 'multimedia', component: Music },
  { name: 'headphones',     labelZh: '耳機音訊',   labelEn: 'Headphones',     category: 'multimedia', component: Headphones },
  { name: 'mic',            labelZh: '麥克風收音', labelEn: 'Microphone',     category: 'multimedia', component: Mic },
  { name: 'speaker',        labelZh: '揚聲喇叭',   labelEn: 'Speaker',        category: 'multimedia', component: Speaker },
  { name: 'disc',           labelZh: '黑膠光碟',   labelEn: 'Vinyl Disc',     category: 'multimedia', component: Disc },
  { name: 'play',           labelZh: '播放按鈕',   labelEn: 'Play Button',    category: 'multimedia', component: Play },

  // ── 工作經歷與商業 ──
  { name: 'briefcase',      labelZh: '產業公事包', labelEn: 'Briefcase Work', category: 'business', component: Briefcase },
  { name: 'building',       labelZh: '企業大樓',   labelEn: 'Building Corp',  category: 'business', component: Building },
  { name: 'building-2',     labelZh: '商辦機構',   labelEn: 'Office Building',category: 'business', component: Building2 },
  { name: 'factory',        labelZh: '工廠製造',   labelEn: 'Factory Plant',  category: 'business', component: Factory },
  { name: 'store',          labelZh: '商業門市',   labelEn: 'Store Shop',     category: 'business', component: Store },
  { name: 'compass',        labelZh: '指針羅盤',   labelEn: 'Compass Nav',    category: 'business', component: Compass },
  { name: 'target',         labelZh: '專案目標',   labelEn: 'Project Target', category: 'business', component: Target },
  { name: 'rocket',         labelZh: '火箭啟航',   labelEn: 'Rocket Launch',  category: 'business', component: Rocket },
  { name: 'lightbulb',      labelZh: '創意靈感',   labelEn: 'Idea Lightbulb', category: 'business', component: Lightbulb },
  { name: 'zap',            labelZh: '極速執行',   labelEn: 'Lightning Zap',  category: 'business', component: Zap },
  { name: 'trending-up',    labelZh: '效能成長',   labelEn: 'Trending Up',    category: 'business', component: TrendingUp },
  { name: 'credit-card',    labelZh: '信用卡商務', labelEn: 'Credit Card',    category: 'business', component: CreditCard },
  { name: 'dollar-sign',    labelZh: '金融金流',   labelEn: 'Dollar Currency',category: 'business', component: DollarSign },
  { name: 'wallet',         labelZh: '數位錢包',   labelEn: 'Digital Wallet', category: 'business', component: Wallet },
  { name: 'percent',        labelZh: '百分比例',   labelEn: 'Percentage',     category: 'business', component: Percent },
  { name: 'receipt',        labelZh: '帳單收據',   labelEn: 'Receipt Invoice',category: 'business', component: Receipt },
  { name: 'megaphone',      labelZh: '行銷擴音',   labelEn: 'Megaphone',      category: 'business', component: Megaphone },
  { name: 'flag',           labelZh: '旗標標竿',   labelEn: 'Flag Milestone', category: 'business', component: Flag },

  // ── 雲端、資安與系統 ──
  { name: 'cloud',          labelZh: '雲端運算',   labelEn: 'Cloud Storage',  category: 'security', component: Cloud },
  { name: 'shield',         labelZh: '資安防護盾', labelEn: 'Security Shield',category: 'security', component: Shield },
  { name: 'shield-check',   labelZh: '資安核可驗證',labelEn: 'Verified Shield',category: 'security', component: ShieldCheck },
  { name: 'shield-alert',   labelZh: '資安警告',   labelEn: 'Shield Alert',   category: 'security', component: ShieldAlert },
  { name: 'lock',           labelZh: '資料加密鎖', labelEn: 'Crypto Lock',    category: 'security', component: Lock },
  { name: 'unlock',         labelZh: '解鎖狀態',   labelEn: 'Unlocked',       category: 'security', component: Unlock },
  { name: 'key',            labelZh: '存取金鑰',   labelEn: 'Access Key',     category: 'security', component: Key },
  { name: 'bell',           labelZh: '通知提醒',   labelEn: 'Notification',   category: 'security', component: Bell },
  { name: 'radio',          labelZh: '廣播天線',   labelEn: 'Radio Broadcast',category: 'security', component: Radio },

  // ── 工具、度量與控制 ──
  { name: 'wrench',         labelZh: '工具工程',   labelEn: 'Wrench Tool',    category: 'tools', component: Wrench },
  { name: 'settings',       labelZh: '系統齒輪',   labelEn: 'Settings Gear',  category: 'tools', component: Settings },
  { name: 'settings-2',     labelZh: '控制設定',   labelEn: 'Settings 2',     category: 'tools', component: Settings2 },
  { name: 'sliders',        labelZh: '滑桿微調',   labelEn: 'Sliders',        category: 'tools', component: Sliders },
  { name: 'sliders-horizontal',labelZh:'水平控制', labelEn: 'Sliders Horiz',  category: 'tools', component: SlidersHorizontal },
  { name: 'activity',       labelZh: '即時脈動',   labelEn: 'Live Activity',  category: 'tools', component: Activity },
  { name: 'gauge',          labelZh: '儀表度量',   labelEn: 'Gauge Meter',    category: 'tools', component: Gauge },
  { name: 'bar-chart',      labelZh: '長條圖表',   labelEn: 'Bar Chart',      category: 'tools', component: BarChart },
  { name: 'bar-chart-2',    labelZh: '數據柱狀圖', labelEn: 'Bar Chart 2',    category: 'tools', component: BarChart2 },
  { name: 'pie-chart',      labelZh: '圓餅圖表',   labelEn: 'Pie Chart',      category: 'tools', component: PieChart },
  { name: 'line-chart',     labelZh: '折線走勢圖', labelEn: 'Line Chart',     category: 'tools', component: LineChart },
  { name: 'filter',         labelZh: '漏斗篩選',   labelEn: 'Filter',         category: 'tools', component: Filter },
  { name: 'search',         labelZh: '放大搜尋',   labelEn: 'Search Glass',   category: 'tools', component: Search },
  { name: 'refresh-cw',     labelZh: '重新同步',   labelEn: 'Refresh Sync',   category: 'tools', component: RefreshCw },
  { name: 'package',        labelZh: '發布軟體包', labelEn: 'Software Package',category: 'tools', component: Package },
  { name: 'archive',        labelZh: '封存歸檔',   labelEn: 'Archive',        category: 'tools', component: Archive },

  // ── 個人、通訊與通用 ──
  { name: 'user',           labelZh: '個人檔案',   labelEn: 'User Profile',   category: 'general', component: User },
  { name: 'users',          labelZh: '團隊合作',   labelEn: 'Team Users',     category: 'general', component: Users },
  { name: 'heart',          labelZh: '熱忱愛心',   labelEn: 'Passion Heart',  category: 'general', component: Heart },
  { name: 'thumbs-up',      labelZh: '好評肯定',   labelEn: 'Thumbs Up',      category: 'general', component: ThumbsUp },
  { name: 'smile',          labelZh: '微笑表情',   labelEn: 'Smile',          category: 'general', component: Smile },
  { name: 'mail',           labelZh: '電子信箱',   labelEn: 'Email Mail',     category: 'general', component: Mail },
  { name: 'phone',          labelZh: '聯絡電話',   labelEn: 'Phone Call',     category: 'general', component: Phone },
  { name: 'message-square', labelZh: '留言即時通訊',labelEn: 'Instant Message',category: 'general', component: MessageSquare },
  { name: 'message-circle', labelZh: '圓形對話框', labelEn: 'Chat Circle',    category: 'general', component: MessageCircle },
  { name: 'send',           labelZh: '發送訊息',   labelEn: 'Send Message',   category: 'general', component: Send },
  { name: 'at-sign',        labelZh: '提及符號',   labelEn: 'At Sign @',      category: 'general', component: AtSign },
  { name: 'map-pin',        labelZh: '地理標籤',   labelEn: 'Map Pin Location',category: 'general', component: MapPin },
  { name: 'navigation',     labelZh: '方向導航',   labelEn: 'Navigation',     category: 'general', component: Navigation },
  { name: 'calendar',       labelZh: '行事曆日程', labelEn: 'Calendar Date',  category: 'general', component: Calendar },
  { name: 'clock',          labelZh: '時鐘時間',   labelEn: 'Clock Time',     category: 'general', component: Clock },
  { name: 'history',        labelZh: '歷史歷程',   labelEn: 'Milestone History',category: 'general', component: History },
  { name: 'file-text',      labelZh: '文件檔案',   labelEn: 'Document Text',  category: 'general', component: FileText },
  { name: 'file-spreadsheet',labelZh:'試算表檔案', labelEn: 'File Spreadsheet',category: 'general', component: FileSpreadsheet },
  { name: 'file-check',     labelZh: '核定文件',   labelEn: 'File Approved',  category: 'general', component: FileCheck },
  { name: 'folder',         labelZh: '一般資料夾', labelEn: 'Folder',         category: 'general', component: Folder },
  { name: 'link',           labelZh: '超連結',     labelEn: 'Hyperlink',      category: 'general', component: Link },
  { name: 'external-link',  labelZh: '外部跳轉連結',labelEn: 'External Link', category: 'general', component: ExternalLink },
  { name: 'share-2',        labelZh: '社群分享',   labelEn: 'Social Share',   category: 'general', component: Share2 },
  { name: 'rss',            labelZh: '訂閱串流',   labelEn: 'RSS Feed',       category: 'general', component: Rss },
  { name: 'eye',            labelZh: '檢視預覽',   labelEn: 'Eye View',       category: 'general', component: Eye },
  { name: 'eye-off',        labelZh: '遮蔽隱藏',   labelEn: 'Eye Off',        category: 'general', component: EyeOff },
  { name: 'check',          labelZh: '勾選記號',   labelEn: 'Check Mark',     category: 'general', component: Check },
  { name: 'check-circle',   labelZh: '核取圓框',   labelEn: 'Check Circle',   category: 'general', component: CheckCircle },
  { name: 'check-square',   labelZh: '核對方塊',   labelEn: 'Check Square',   category: 'general', component: CheckSquare },
  { name: 'x',              labelZh: '叉叉關閉',   labelEn: 'Close X',        category: 'general', component: X },
  { name: 'x-circle',       labelZh: '錯誤圓框',   labelEn: 'Close Circle',   category: 'general', component: XCircle },
  { name: 'alert-triangle', labelZh: '警示注意',   labelEn: 'Alert Warning',  category: 'general', component: AlertTriangle },
  { name: 'alert-circle',   labelZh: '警訊提示',   labelEn: 'Alert Circle',   category: 'general', component: AlertCircle },
  { name: 'info',           labelZh: '資訊說明',   labelEn: 'Info Note',      category: 'general', component: Info },
  { name: 'help-circle',    labelZh: '幫助說明',   labelEn: 'Help Circle',    category: 'general', component: HelpCircle },
  { name: 'sun',            labelZh: '太陽日間',   labelEn: 'Sun Day',        category: 'general', component: Sun },
  { name: 'moon',           labelZh: '月亮夜間',   labelEn: 'Moon Night',     category: 'general', component: Moon },
  { name: 'flame',          labelZh: '熱門烈焰',   labelEn: 'Flame Fire',     category: 'general', component: Flame },
  { name: 'droplet',        labelZh: '水滴流暢',   labelEn: 'Water Droplet',  category: 'general', component: Droplet },
  { name: 'coffee',         labelZh: '咖啡休息',   labelEn: 'Coffee Break',   category: 'general', component: Coffee },
  { name: 'maximize',       labelZh: '全螢幕最大化',labelEn: 'Maximize',      category: 'general', component: Maximize },
  { name: 'minimize',       labelZh: '最小化視窗', labelEn: 'Minimize',       category: 'general', component: Minimize },
  { name: 'move',           labelZh: '四向移動',   labelEn: 'Move 4-way',     category: 'general', component: Move },
  { name: 'volume-2',       labelZh: '音量全開',   labelEn: 'Volume High',    category: 'general', component: Volume2 },
  { name: 'volume-1',       labelZh: '音量適中',   labelEn: 'Volume Low',     category: 'general', component: Volume1 },
];

/** 根據名稱尋找 Icon 組件的 Helper (支援別名與語意自動推斷) */
export const getLucideIconByName = (name: string): LucideIcon => {
  if (!name) return Star;
  const normalized = name.toLowerCase().replace(/_/g, '-').trim();
  const found = ICON_LIBRARY.find(
    (item) => item.name === normalized || item.name.replace(/-/g, '') === normalized.replace(/-/g, '')
  );
  if (found) return found.component;

  // 語意別名對照表：確保各領域圖示具備高度視覺區隔度
  const aliasMap: Record<string, LucideIcon> = {
    game: Gamepad2,
    gaming: Gamepad2,
    gamepad: Gamepad2,
    box: Box,
    '3d': Box,
    code: Code2,
    dev: Code2,
    video: Video,
    school: School,
    academic: School,
    master: GraduationCap,
    bachelor: School,
    degree: GraduationCap,
    grad: GraduationCap,
    cert: Award,
    certificate: Award,
    certification: Award,
    paper: FileText,
    thesis: FileText,
    publication: Scroll,
    conference: Presentation,
    workshop: Presentation,
    speech: Presentation,
    award: Award,
    trophy: Trophy,
    rank: Medal,
    transcript: Scroll,
    diploma: GraduationCap,
    work: Briefcase,
    job: Briefcase,
    company: Building,
    phone: Phone,
    email: Mail,
    line: MessageSquare,
  };

  return aliasMap[normalized] || Star;
};
